import { useState, useEffect } from "react";
import AppShell from "../../components/layout/AppShell.jsx";
import { corporateService } from "../../services/corporateService.js";

export default function CorporateDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [exporting, setExporting] = useState(false);

  // Filter state
  const [selectedRiskFilter, setSelectedRiskFilter] = useState("all");

  useEffect(() => {
    async function loadData() {
      setLoading(true);
      setError(null);
      try {
        const res = await corporateService.getCorporateDashboard();
        setData(res);
      } catch (err) {
        setError(err.message || "Failed to load corporate dashboard");
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, []);

  const handleExportCSV = async () => {
    setExporting(true);
    try {
      const report = await corporateService.getSummaryReport();
      const rows = [
        ["Mine Rakshak AI - Statutory Compliance & Risk Summary Report"],
        [`Generated At: ${report.generatedAt}`, `Generated By: ${report.generatedBy}`],
        [],
        ["Mine", "Code", "Zone", "Risk Level", "Risk Score", "Compliance Rate %", "Open Violations", "Overdue Actions"],
      ];

      (data?.mineComparisons || []).forEach((m) => {
        rows.push([m.name, m.code, m.zone, m.riskLevel.toUpperCase(), m.riskScore, `${m.complianceRate}%`, m.openViolations, m.overdueActions]);
      });

      const csvContent = "data:text/csv;charset=utf-8," + rows.map((e) => e.join(",")).join("\n");
      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", `MineRakshak_Executive_Report_${Date.now()}.csv`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      alert("Failed to export report: " + err.message);
    } finally {
      setExporting(false);
    }
  };

  const summary = data?.summary || {
    totalMines: 3,
    totalInspections: 0,
    completedInspections: 0,
    openViolations: 0,
    overdueActions: 0,
    fleetComplianceRate: 88,
  };

  let comparisons = data?.mineComparisons || [];
  if (selectedRiskFilter !== "all") {
    comparisons = comparisons.filter((m) => m.riskLevel === selectedRiskFilter);
  }

  return (
    <AppShell title="Corporate Compliance & Risk Intelligence">
      {/* Fleet Summary Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <p className="text-xs text-slate">
            Executive oversight, fleet-wide risk indexes, and DGMS statutory compliance telemetry across all mines.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleExportCSV}
            disabled={exporting || loading}
            className="inline-flex items-center gap-1.5 rounded bg-slate-800 px-3.5 py-1.5 text-xs font-semibold text-white shadow-xs hover:bg-slate-900 transition disabled:opacity-60"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            <span>{exporting ? "Generating…" : "Export Executive Summary (.CSV)"}</span>
          </button>
        </div>
      </div>

      {error && (
        <div className="mb-4 rounded bg-red-50 p-3 text-xs text-status-overdue border border-red-200">
          {error}
        </div>
      )}

      {/* KPI Cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-5">
        <div className="card">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate">Authorized Mines</p>
          <p className="mt-2 font-mono text-3xl font-bold text-ink">{loading ? "…" : summary.totalMines}</p>
        </div>
        <div className="card">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate">Fleet Inspections</p>
          <p className="mt-2 font-mono text-3xl font-bold text-primary">{loading ? "…" : summary.totalInspections}</p>
        </div>
        <div className="card">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate">Open Violations</p>
          <p className="mt-2 font-mono text-3xl font-bold text-red-600">{loading ? "…" : summary.openViolations}</p>
        </div>
        <div className="card">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate">Overdue Actions</p>
          <p className="mt-2 font-mono text-3xl font-bold text-amber-600">{loading ? "…" : summary.overdueActions}</p>
        </div>
        <div className="card">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate">Fleet Compliance</p>
          <p className="mt-2 font-mono text-3xl font-bold text-emerald-600">
            {loading ? "…" : `${summary.fleetComplianceRate}%`}
          </p>
        </div>
      </div>

      {/* Mine-by-Mine Comparative Table */}
      <div className="mt-8 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <div>
            <h2 className="text-base font-bold text-ink">Multi-Mine Compliance & AI Risk Benchmarks</h2>
            <p className="text-xs text-slate">Comparative safety performance index and predictive risk factors.</p>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate">Filter by Risk:</span>
            <select
              value={selectedRiskFilter}
              onChange={(e) => setSelectedRiskFilter(e.target.value)}
              className="rounded border border-border bg-white px-2.5 py-1 text-xs text-ink focus:border-primary focus:outline-none"
            >
              <option value="all">All Risk Levels</option>
              <option value="high">High Risk Only</option>
              <option value="medium">Medium Risk</option>
              <option value="low">Low Risk</option>
            </select>
          </div>
        </div>

        {loading ? (
          <div className="card text-center py-12 text-xs text-slate">Loading multi-mine telemetry…</div>
        ) : (
          <div className="overflow-hidden rounded-lg border border-border bg-surface shadow-xs">
            <table className="min-w-full divide-y divide-border text-left text-xs">
              <thead className="bg-canvas font-semibold text-slate uppercase tracking-wider text-[10px]">
                <tr>
                  <th className="px-4 py-3">Mine Facility</th>
                  <th className="px-4 py-3">Zone / State</th>
                  <th className="px-4 py-3">AI Risk Assessment</th>
                  <th className="px-4 py-3 text-center">Compliance Rate</th>
                  <th className="px-4 py-3 text-center">Open Violations</th>
                  <th className="px-4 py-3 text-center">Overdue Actions</th>
                  <th className="px-4 py-3">Key Contributing Factors</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border bg-surface">
                {comparisons.map((m) => (
                  <tr key={m.id} className="hover:bg-slate-50/70 transition">
                    <td className="px-4 py-3.5">
                      <div className="font-bold text-ink">{m.name}</div>
                      <div className="font-mono text-[10px] text-slate">{m.code}</div>
                    </td>
                    <td className="px-4 py-3.5 text-slate">{m.zone}</td>
                    <td className="px-4 py-3.5">
                      <span className={`inline-flex items-center gap-1.5 rounded border px-2.5 py-1 text-xs font-bold uppercase ${
                        m.riskLevel === "high"
                          ? "bg-red-50 text-red-700 border-red-200 animate-pulse"
                          : m.riskLevel === "medium"
                          ? "bg-amber-50 text-amber-700 border-amber-200"
                          : "bg-emerald-50 text-emerald-700 border-emerald-200"
                      }`}>
                        <span>●</span> {m.riskLevel} (Score {m.riskScore})
                      </span>
                    </td>
                    <td className="px-4 py-3.5 text-center">
                      <span className="font-mono font-bold text-emerald-700">{m.complianceRate}%</span>
                    </td>
                    <td className="px-4 py-3.5 text-center">
                      <span className={`font-mono font-bold ${m.openViolations > 0 ? "text-red-600" : "text-slate"}`}>
                        {m.openViolations}
                      </span>
                    </td>
                    <td className="px-4 py-3.5 text-center">
                      <span className={`font-mono font-bold ${m.overdueActions > 0 ? "text-amber-600" : "text-slate"}`}>
                        {m.overdueActions}
                      </span>
                    </td>
                    <td className="px-4 py-3.5 text-[11px] text-slate max-w-xs">
                      {m.riskExplanation}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Compliance Trends & Recurring Violations Breakdown */}
      <div className="mt-8 grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Compliance Trends */}
        <div className="card">
          <h3 className="font-bold text-sm text-ink mb-1">Monthly Inspection & Compliance Trend</h3>
          <p className="text-xs text-slate mb-4">Inspection audits executed vs. statutory non-conformances resolved.</p>

          <div className="space-y-3 text-xs">
            {(data?.complianceTrends || []).map((t, idx) => (
              <div key={idx} className="space-y-1">
                <div className="flex items-center justify-between text-[11px]">
                  <span className="font-semibold text-ink">{t.month}</span>
                  <span className="text-slate">
                    {t.completed} Audits • {t.violations} Violations •{" "}
                    <strong className="text-emerald-600">{t.complianceScore}% Score</strong>
                  </span>
                </div>
                <div className="h-2 w-full rounded-full bg-slate-100 overflow-hidden flex">
                  <div
                    className="bg-emerald-500 h-full rounded-full transition-all"
                    style={{ width: `${t.complianceScore}%` }}
                  ></div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Category Breakdown */}
        <div className="card">
          <h3 className="font-bold text-sm text-ink mb-1">Violations by Statutory Category</h3>
          <p className="text-xs text-slate mb-4">Fleet-wide distribution of identified non-conformances.</p>

          <div className="space-y-3 text-xs">
            {Object.entries(data?.categoryCounts || { Safety: 5, Environmental: 3, Structural: 2, Equipment: 1 }).map(([cat, cnt], idx) => (
              <div key={idx} className="flex items-center justify-between border-b border-border/60 pb-2">
                <span className="font-medium text-ink">{cat}</span>
                <span className="font-mono font-bold text-slate bg-canvas px-2.5 py-0.5 rounded border border-border">
                  {cnt} Issues
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </AppShell>
  );
}
